### ISSUE TITLE
[docker-compose.yml] Add networks in docker-compose.yml

### ISSUE THREAD

**Issue by hitohiros** [Mata-Elang-Stable/MataElang-Confluent#2]
Add the fixed networks address in docker-compose.yml like below to make it easier to build a firewall on a host.
```
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.21.0.0/16"
```
then, add the iptable forwarding rules like below.
```
iptables -I DOCKER-USER -i ens3 -p tcp --dport 5601 -d 172.21.0.0/16 -s 0.0.0.0/0 -j DROP
iptables -I DOCKER-USER -i ens3 -p tcp --dport 5601 -d 172.21.0.0/16 -s 153.242.161.132 -j ACCEPT
```

*Reference: Docker and ufw serious problems (note: problem explanation only. solution is different)
https://github.com/moby/moby/issues/4737
